#DO NOT FORGET
#export $(grep -v '^#' .env | xargs)
services:
  infra:
    path: infra
    params:
      userPoolName: ${sls:stage}-${env:USER_POOL}
      siteTable: ${sls:stage}-${env:SITES_TABLE}
      siteBucket: ${sls:stage}-${env:SITES_BUCKET}

  site:
    path: site
    dependsOn: infra
    params:
      sitesTableArn: ${infra.SitesTableArn}
      sitesBucketName: ${infra.SitesBucketName}
      userPoolID: ${infra.CognitoUserPoolID}
      clientPoolId1: ${infra.CognitoAppClientID}
      siteTable: ${sls:stage}-${env:SITES_TABLE}
      HttpApiId: ${infra.HttpApiId}
      jwtAuthorizer: ${infra.JWTAuthorizerId}



#  payment:
#    path: payment
#    dependsOn: infra

